// Copyright 2026 Nopparuj Ananvoranich
// SPDX-License-Identifier: Apache-2.0

// General MIDI Level 1 patch and percussion-key names, for populating a
// picker UI - not consumed by to-midi.mjs itself, which keeps its own small
// Thai-name-matching default tables. Names are the GM1 standard's own
// English names; there's no established Thai equivalent to translate them
// to.

/** The 16 GM families, in GM's own order, each with its 8 programs (1-indexed). */
export const GM_INSTRUMENT_FAMILIES = [
  {
    family: "Piano",
    instruments: [
      { program: 1, name: "Acoustic Grand Piano" },
      { program: 2, name: "Bright Acoustic Piano" },
      { program: 3, name: "Electric Grand Piano" },
      { program: 4, name: "Honky-tonk Piano" },
      { program: 5, name: "Electric Piano 1" },
      { program: 6, name: "Electric Piano 2" },
      { program: 7, name: "Harpsichord" },
      { program: 8, name: "Clavinet" },
    ],
  },
  {
    family: "Chromatic Percussion",
    instruments: [
      { program: 9, name: "Celesta" },
      { program: 10, name: "Glockenspiel" },
      { program: 11, name: "Music Box" },
      { program: 12, name: "Vibraphone" },
      { program: 13, name: "Marimba" },
      { program: 14, name: "Xylophone" },
      { program: 15, name: "Tubular Bells" },
      { program: 16, name: "Dulcimer" },
    ],
  },
  {
    family: "Organ",
    instruments: [
      { program: 17, name: "Drawbar Organ" },
      { program: 18, name: "Percussive Organ" },
      { program: 19, name: "Rock Organ" },
      { program: 20, name: "Church Organ" },
      { program: 21, name: "Reed Organ" },
      { program: 22, name: "Accordion" },
      { program: 23, name: "Harmonica" },
      { program: 24, name: "Tango Accordion" },
    ],
  },
  {
    family: "Guitar",
    instruments: [
      { program: 25, name: "Acoustic Guitar (nylon)" },
      { program: 26, name: "Acoustic Guitar (steel)" },
      { program: 27, name: "Electric Guitar (jazz)" },
      { program: 28, name: "Electric Guitar (clean)" },
      { program: 29, name: "Electric Guitar (muted)" },
      { program: 30, name: "Overdriven Guitar" },
      { program: 31, name: "Distortion Guitar" },
      { program: 32, name: "Guitar Harmonics" },
    ],
  },
  {
    family: "Bass",
    instruments: [
      { program: 33, name: "Acoustic Bass" },
      { program: 34, name: "Electric Bass (finger)" },
      { program: 35, name: "Electric Bass (pick)" },
      { program: 36, name: "Fretless Bass" },
      { program: 37, name: "Slap Bass 1" },
      { program: 38, name: "Slap Bass 2" },
      { program: 39, name: "Synth Bass 1" },
      { program: 40, name: "Synth Bass 2" },
    ],
  },
  {
    family: "Strings",
    instruments: [
      { program: 41, name: "Violin" },
      { program: 42, name: "Viola" },
      { program: 43, name: "Cello" },
      { program: 44, name: "Contrabass" },
      { program: 45, name: "Tremolo Strings" },
      { program: 46, name: "Pizzicato Strings" },
      { program: 47, name: "Orchestral Harp" },
      { program: 48, name: "Timpani" },
    ],
  },
  {
    family: "Ensemble",
    instruments: [
      { program: 49, name: "String Ensemble 1" },
      { program: 50, name: "String Ensemble 2" },
      { program: 51, name: "Synth Strings 1" },
      { program: 52, name: "Synth Strings 2" },
      { program: 53, name: "Choir Aahs" },
      { program: 54, name: "Voice Oohs" },
      { program: 55, name: "Synth Voice" },
      { program: 56, name: "Orchestra Hit" },
    ],
  },
  {
    family: "Brass",
    instruments: [
      { program: 57, name: "Trumpet" },
      { program: 58, name: "Trombone" },
      { program: 59, name: "Tuba" },
      { program: 60, name: "Muted Trumpet" },
      { program: 61, name: "French Horn" },
      { program: 62, name: "Brass Section" },
      { program: 63, name: "Synth Brass 1" },
      { program: 64, name: "Synth Brass 2" },
    ],
  },
  {
    family: "Reed",
    instruments: [
      { program: 65, name: "Soprano Sax" },
      { program: 66, name: "Alto Sax" },
      { program: 67, name: "Tenor Sax" },
      { program: 68, name: "Baritone Sax" },
      { program: 69, name: "Oboe" },
      { program: 70, name: "English Horn" },
      { program: 71, name: "Bassoon" },
      { program: 72, name: "Clarinet" },
    ],
  },
  {
    family: "Pipe",
    instruments: [
      { program: 73, name: "Piccolo" },
      { program: 74, name: "Flute" },
      { program: 75, name: "Recorder" },
      { program: 76, name: "Pan Flute" },
      { program: 77, name: "Blown Bottle" },
      { program: 78, name: "Shakuhachi" },
      { program: 79, name: "Whistle" },
      { program: 80, name: "Ocarina" },
    ],
  },
  {
    family: "Synth Lead",
    instruments: [
      { program: 81, name: "Lead 1 (square)" },
      { program: 82, name: "Lead 2 (sawtooth)" },
      { program: 83, name: "Lead 3 (calliope)" },
      { program: 84, name: "Lead 4 (chiff)" },
      { program: 85, name: "Lead 5 (charang)" },
      { program: 86, name: "Lead 6 (voice)" },
      { program: 87, name: "Lead 7 (fifths)" },
      { program: 88, name: "Lead 8 (bass + lead)" },
    ],
  },
  {
    family: "Synth Pad",
    instruments: [
      { program: 89, name: "Pad 1 (new age)" },
      { program: 90, name: "Pad 2 (warm)" },
      { program: 91, name: "Pad 3 (polysynth)" },
      { program: 92, name: "Pad 4 (choir)" },
      { program: 93, name: "Pad 5 (bowed)" },
      { program: 94, name: "Pad 6 (metallic)" },
      { program: 95, name: "Pad 7 (halo)" },
      { program: 96, name: "Pad 8 (sweep)" },
    ],
  },
  {
    family: "Synth Effects",
    instruments: [
      { program: 97, name: "FX 1 (rain)" },
      { program: 98, name: "FX 2 (soundtrack)" },
      { program: 99, name: "FX 3 (crystal)" },
      { program: 100, name: "FX 4 (atmosphere)" },
      { program: 101, name: "FX 5 (brightness)" },
      { program: 102, name: "FX 6 (goblins)" },
      { program: 103, name: "FX 7 (echoes)" },
      { program: 104, name: "FX 8 (sci-fi)" },
    ],
  },
  {
    family: "Ethnic",
    instruments: [
      { program: 105, name: "Sitar" },
      { program: 106, name: "Banjo" },
      { program: 107, name: "Shamisen" },
      { program: 108, name: "Koto" },
      { program: 109, name: "Kalimba" },
      { program: 110, name: "Bag Pipe" },
      { program: 111, name: "Fiddle" },
      { program: 112, name: "Shanai" },
    ],
  },
  {
    family: "Percussive",
    instruments: [
      { program: 113, name: "Tinkle Bell" },
      { program: 114, name: "Agogo" },
      { program: 115, name: "Steel Drums" },
      { program: 116, name: "Woodblock" },
      { program: 117, name: "Taiko Drum" },
      { program: 118, name: "Melodic Tom" },
      { program: 119, name: "Synth Drum" },
      { program: 120, name: "Reverse Cymbal" },
    ],
  },
  {
    family: "Sound Effects",
    instruments: [
      { program: 121, name: "Guitar Fret Noise" },
      { program: 122, name: "Breath Noise" },
      { program: 123, name: "Seashore" },
      { program: 124, name: "Bird Tweet" },
      { program: 125, name: "Telephone Ring" },
      { program: 126, name: "Helicopter" },
      { program: 127, name: "Applause" },
      { program: 128, name: "Gunshot" },
    ],
  },
];

/** GM's standard percussion key map (channel 10), notes 35-81. */
export const GM_PERCUSSION_NOTES = [
  { note: 35, name: "Acoustic Bass Drum" },
  { note: 36, name: "Bass Drum 1" },
  { note: 37, name: "Side Stick" },
  { note: 38, name: "Acoustic Snare" },
  { note: 39, name: "Hand Clap" },
  { note: 40, name: "Electric Snare" },
  { note: 41, name: "Low Floor Tom" },
  { note: 42, name: "Closed Hi-Hat" },
  { note: 43, name: "High Floor Tom" },
  { note: 44, name: "Pedal Hi-Hat" },
  { note: 45, name: "Low Tom" },
  { note: 46, name: "Open Hi-Hat" },
  { note: 47, name: "Low-Mid Tom" },
  { note: 48, name: "Hi-Mid Tom" },
  { note: 49, name: "Crash Cymbal 1" },
  { note: 50, name: "High Tom" },
  { note: 51, name: "Ride Cymbal 1" },
  { note: 52, name: "Chinese Cymbal" },
  { note: 53, name: "Ride Bell" },
  { note: 54, name: "Tambourine" },
  { note: 55, name: "Splash Cymbal" },
  { note: 56, name: "Cowbell" },
  { note: 57, name: "Crash Cymbal 2" },
  { note: 58, name: "Vibraslap" },
  { note: 59, name: "Ride Cymbal 2" },
  { note: 60, name: "Hi Bongo" },
  { note: 61, name: "Low Bongo" },
  { note: 62, name: "Mute Hi Conga" },
  { note: 63, name: "Open Hi Conga" },
  { note: 64, name: "Low Conga" },
  { note: 65, name: "High Timbale" },
  { note: 66, name: "Low Timbale" },
  { note: 67, name: "High Agogo" },
  { note: 68, name: "Low Agogo" },
  { note: 69, name: "Cabasa" },
  { note: 70, name: "Maracas" },
  { note: 71, name: "Short Whistle" },
  { note: 72, name: "Long Whistle" },
  { note: 73, name: "Short Guiro" },
  { note: 74, name: "Long Guiro" },
  { note: 75, name: "Claves" },
  { note: 76, name: "Hi Wood Block" },
  { note: 77, name: "Low Wood Block" },
  { note: 78, name: "Mute Cuica" },
  { note: 79, name: "Open Cuica" },
  { note: 80, name: "Mute Triangle" },
  { note: 81, name: "Open Triangle" },
];
